services:
  postgres17-local:
    image: postgres:17.6
    container_name: postgres17-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma-studio:
    build:
      context: .
      dockerfile: prisma.Dockerfile
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - postgres17-local

volumes:
  postgres_data:
